title: Voila!
author: Charles.W
email: dancerww@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nothing to see here, please move along.

# social links
twitter_username: dancerww
github_username:  dancerww

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
